######################################################################
# Automatically generated by qmake (3.0) Fri Dec 11 16:10:53 2020
######################################################################

TEMPLATE = app
TARGET = Scene
INCLUDEPATH += . /opt/local/include

QT += widgets opengl gui

LIBS += -lglut -lGLU

# Input
HEADERS += SceneWidget.h SceneWindow.h Image.h
SOURCES += SceneMain.cpp \
           SceneWidget.cpp \
           SceneWindow.cpp \
           Image.cpp
